In [1]:
#import libraries
!pip install tmdbv3api
import pandas as pd
import numpy as np
from tmdbv3api import TMDb
import json
import requests
from tmdbv3api import Movie

#My TMDB API KEY
tmdb = TMDb()
tmdb.api_key = '946350b18b862d23ce1763b947a7e3e1'

Requirement already satisfied: tmdbv3api in c:\users\yash sharma\anaconda33\lib\site-packages (1.7.6)
Requirement already satisfied: requests in c:\users\yash sharma\anaconda33\lib\site-packages (from tmdbv3api) (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yash sharma\anaconda33\lib\site-packages (from requests->tmdbv3api) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\yash sharma\anaconda33\lib\site-packages (from requests->tmdbv3api) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\yash sharma\anaconda33\lib\site-packages (from requests->tmdbv3api) (1.25.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\yash sharma\anaconda33\lib\site-packages (from requests->tmdbv3api) (3.0.4)

WARNING: Ignoring invalid distribution -umpy (c:\users\yash sharma\anaconda33\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\yash sharma\anaconda33\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\yash sharma\anaconda33\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\yash sharma\anaconda33\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\yash sharma\anaconda33\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\yash sharma\anaconda33\lib\site-packages)

## Functions for data collection and preprocessing

In [ ]:
#function for fetching movie id
from tmdbv3api import Movie
tmdb_movie = Movie() 
def get_id(x):
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      return result[0].id

In [2]:
#function for fetching genres
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['genres']:
          genre_str = " " 
          for i in range(0,len(data_json['genres'])):
              genres.append(data_json['genres'][i]['name'])
          return genre_str.join(genres)
      else:
          return np.NaN

In [ ]:
#function for fetching keywords
 def get_keywords(x):
    keywords = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}/keywords?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['keywords']:
          keywords_str = " " 
          for i in range(0,len(data_json['keywords'])):
              keywords.append(data_json['keywords'][i]['name'])
          return keywords_str.join(keywords)
      else:
          return np.NaN

In [ ]:
#function for fetching overview score of movie
def get_overview(x):
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['overview']:
          return data_json['overview']
      else:
          return np.NaN

In [ ]:
#function for fetching overview score of movie
def get_tagline(x):
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['tagline']:
          return data_json['tagline']
      else:
          return np.NaN

In [3]:
#function for fetching popularity score of movie
def get_popularity(x):
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['popularity']:
          return data_json['popularity']
      else:
          return np.NaN

In [4]:
#function for fetching vote average of movie
def get_vote_average(x):
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['vote_average']:
          return data_json['vote_average']
      else:
          return np.NaN

In [ ]:
#function for fetching popularity score of movie
def get_vote_count(x):
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['vote_count']:
          return data_json['vote_count']
      else:
          return np.NaN

In [5]:
#functions for fetching cast name
def get_actor1(x):
    if type(x)==float:
        return np.NaN
    return ((x.split(", ")[0]))

def get_actor2(x):
    
    if type(x)==float or len(x.split(", ")) < 2:
        return np.NaN
    else:
        return (x.split(", ")[1])

def get_actor3(x):
    if type(x)==float or len(x.split(", ")) < 3:
        return np.NaN
    else:
        return (x.split(", ")[2])

In [ ]:
def preprocess_data(df):
    
    #if row has NULL entries we remove it from data
    df.dropna(inplace=True, thresh=11)
    
    df = df.rename(columns={'Title':'movie_title','Director': 'director', 'Genre':'genres'})
    df = df.loc[:,['id','movie_title','keywords','tagline','overview','director','actor_1','actor_2','actor_3','genres','popularity', 'year', 'vote_average','vote_count']]
    
    df['genres'] = df['genres'].replace(np.nan, 'na')
    df['overview'] = df['overview'].replace(np.nan, 'na')
    df['tagline'] = df['tagline'].replace(np.nan, 'na')
    df['keywords'] = df['keywords'].replace(np.nan, 'na')
    df['director'] = df['director'].replace(np.nan, 'unknown')
    df['actor_1'] = df['actor_1'].replace(np.nan, 'unknown')
    df['actor_2'] = df['actor_2'].replace(np.nan, 'unknown')
    df['actor_3'] = df['actor_3'].replace(np.nan, 'unknown')
    df['movie_title'] = df['movie_title'].str.lower()
    df['describe'] = df['keywords'] + ' ' + df['tagline'] + ' ' +df['overview'] + ' '+df['actor_1'] + ' ' + df['actor_2'] + ' '+ df['actor_3'] + ' '+ df['director'] +' ' + df['genres'] + ' ' + df['vote_count']
    
    return df

In [6]:
#function for collecting data of bollywood movies
def get_movie_data(year):
    #get movie data from wikipedia
    link = "https://en.wikipedia.org/wiki/List_of_Hindi_films_of_"+year
    df1 = pd.read_html(link, header=0)[2]
    df2 = pd.read_html(link, header=0)[3]
    df3 = pd.read_html(link, header=0)[4]
    df4 = pd.read_html(link, header=0)[5]
    df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
    
    #fetch genres, popularity of the movie through tmdb api key
    tmdb = TMDb()
    tmdb.api_key = '946350b18b862d23ce1763b947a7e3e1'
    tmdb_movie = Movie() 
    
    #fetch movie id
    df['id'] = df['Title'].map(lambda x: get_id(str(x)))
    
    #fetch keywords
    df['keywords'] = df['Title'].map(lambda x: get_keywords(str(x)))
    
    #fetch tagline
    df['tagline'] = df['Title'].map(lambda x: get_tagline(str(x)))
    
    #fetch overview
    df['overview'] = df['Title'].map(lambda x: get_overview(str(x)))
    
    #fetch Genre
    df['Genre'] = df['Title'].map(lambda x: get_genre(str(x)))
    
    #fetch poplurity
    df['popularity'] = df['Title'].map(lambda x: get_popularity(str(x)))
    
    #fetch vote average
    df['vote_average'] = df['Title'].map(lambda x: get_vote_average(str(x)))
    
    #fetch vote count
    df['vote_count'] = df['Title'].map(lambda x: get_vote_count(str(x)))
    
    #collect required features
    df = df[['id','Title','keywords', 'tagline', 'overview','Director','Cast','Genre','popularity', 'vote_average', 'vote_count']]
    
    #add actors name and release year of the movie
    df['actor_1'] = df['Cast'].map(lambda x: get_actor1(x))
    df['actor_2'] = df['Cast'].map(lambda x: get_actor2(x))
    df['actor_3'] = df['Cast'].map(lambda x: get_actor3(x))
    df['year'] = year
    
    #data preprocess
    data = preprocess_data(df)
    
    return data

## Collecting Movies data released after 2000

In [7]:
#collecting movies of 2000
data = get_movie_data('2000')

C:\Users\Yash Sharma\Anaconda33\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

In [10]:
#collecting movies of 2001
data_2001 = get_movie_data('2001')
data = data.append(data_2001,ignore_index=True)

In [12]:
#collecting movies of 2002
data_2002 = get_movie_data('2002')
data = data.append(data_2002,ignore_index=True)

In [15]:
#collecting movies of 2003
data_2003 = get_movie_data('2003')
data = data.append(data_2003,ignore_index=True)

In [16]:
#collecting movies of 2004
data_2004 = get_movie_data('2004')
data = data.append(data_2004,ignore_index=True)

In [17]:
#collecting movies of 2005
data_2005 = get_movie_data('2005')
data = data.append(data_2005,ignore_index=True)

In [18]:
#collecting movies of 2006
data_2006 = get_movie_data('2006')
data = data.append(data_2006,ignore_index=True)

In [19]:
#collecting movies of 2007
data_2007 = get_movie_data('2007')
data = data.append(data_2007,ignore_index=True)

In [21]:
#collecting movies of 2008
data_2008 = get_movie_data('2008')
data = data.append(data_2008,ignore_index=True)

In [22]:
#collecting movies of 2009
data_2009 = get_movie_data('2009')
data = data.append(data_2009,ignore_index=True)

In [23]:
#collecting movies of 2010
data_2010 = get_movie_data('2010')
data = data.append(data_2010,ignore_index=True)

In [24]:
#collecting movies of 2011
data_2011 = get_movie_data('2011')
data = data.append(data_2011,ignore_index=True)

In [25]:
#collecting movies of 2012
data_2012 = get_movie_data('2012')
data = data.append(data_2012,ignore_index=True)

In [26]:
#collecting movies of 2013
data_2013 = get_movie_data('2013')
data = data.append(data_2013,ignore_index=True)

In [27]:
#collecting movies of 2014
data_2014 = get_movie_data('2014')
data = data.append(data_2014,ignore_index=True)

In [28]:
#collecting movies of 2015
data_2015 = get_movie_data('2015')
data = data.append(data_2015,ignore_index=True)

In [29]:
#collecting movies of 2016
data_2016 = get_movie_data('2016')
data = data.append(data_2016,ignore_index=True)

In [30]:
#collecting movies of 2017
data_2017 = get_movie_data('2017')
data = data.append(data_2017,ignore_index=True)

In [43]:
#collecting movies of 2018
data_2018 = get_movie_data('2018')
data = data.append(data_2018,ignore_index=True)

In [32]:
#collecting movies of 2019
data_2019 = get_movie_data('2019')
data = data.append(data_2019,ignore_index=True)

In [33]:
#collecting movies of 2020
data_2020 = get_movie_data('2020')
data = data.append(data_2020,ignore_index=True)

In [34]:
#collecting movies of 2021
data_2021 = get_movie_data('2021')
data = data.append(data_2021,ignore_index=True)

In [36]:
#collecting movies of 2022
data_2022 = get_movie_data('2022')
data = data.append(data_2022,ignore_index=True)

In [38]:
data

,movie_title,director,actor_1,actor_2,actor_3,genres,popularity,year,ratings,combine
0,kuch kuch hota hai,Karan Johar,Shahrukh Khan,Kajol,Rani Mukerji,Romance Drama,11.704,2000,7.7,Shahrukh Khan Kajol Rani Mukerji Karan Johar R...
1,bichhoo,Guddu Dhanoa,Bobby Deol,Rani Mukerji,Malaika Arora,Action Crime Thriller,1.532,2000,4.8,Bobby Deol Rani Mukerji Malaika Arora Guddu Dh...
2,bulandi,Rama Rao Tatineni,Rajinikanth,Rekha,Anil Kapoor,Drama,1.454,2000,7.0,Rajinikanth Rekha Anil Kapoor Rama Rao Tatinen...
3,chal mere bhai,David Dhawan,Sanjay Dutt,Salman Khan,Karisma Kapoor,Romance Comedy,2.829,2000,4.8,Sanjay Dutt Salman Khan Karisma Kapoor David D...
4,dhadkan,Dharmesh Darshan,Akshay Kumar,Sunil Shetty,Shilpa Shetty,Drama Romance,2.740,2000,6.7,Akshay Kumar Sunil Shetty Shilpa Shetty Dharme...
...,...,...,...,...,...,...,...,...,...,...
1023,a daughter's tale pankh,Premraaj,Nishigandha Wad,Mehul Buch,Sudhir Pandey,Drama,0.600,2017,7.0,Nishigandha Wad Mehul Buch Sudhir Pandey Premr...
1024,kadvi hawa,Nila Madhab Panda,Sanjay Mishra,Ranvir Shorey,Tillotama Shome,Drama,1.201,2017,7.9,Sanjay Mishra Ranvir Shorey Tillotama Shome Ni...
1025,fukrey returns,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy Drama,1.616,2017,6.6,Pulkit Samrat Priya Anand Ali Fazal Mrighdeep ...
1026,game over,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Action Adventure Comedy Family Science Fiction,54.384,2017,5.1,Rajesh Sharma Yashpal Sharma Gurleen Chopra Pa...
1027,blackboard vs whiteboard,Tarun S. Bisht,Raghubir Yadav,Ashok Samarth,Akhilendra Mishra,Family,0.635,2019,7.0,Raghubir Yadav Ashok Samarth Akhilendra Mishra...

In [40]:
data['combine'] = data['combine'] +' ' + data['popularity'].map(str)

In [48]:
data

,movie_title,director,actor_1,actor_2,actor_3,genres,popularity,year,ratings,combine
0,kuch kuch hota hai,Karan Johar,Shahrukh Khan,Kajol,Rani Mukerji,Romance Drama,11.704,2000,7.7,Shahrukh Khan Kajol Rani Mukerji Karan Johar R...
1,bichhoo,Guddu Dhanoa,Bobby Deol,Rani Mukerji,Malaika Arora,Action Crime Thriller,1.532,2000,4.8,Bobby Deol Rani Mukerji Malaika Arora Guddu Dh...
2,bulandi,Rama Rao Tatineni,Rajinikanth,Rekha,Anil Kapoor,Drama,1.454,2000,7.0,Rajinikanth Rekha Anil Kapoor Rama Rao Tatinen...
3,chal mere bhai,David Dhawan,Sanjay Dutt,Salman Khan,Karisma Kapoor,Romance Comedy,2.829,2000,4.8,Sanjay Dutt Salman Khan Karisma Kapoor David D...
4,dhadkan,Dharmesh Darshan,Akshay Kumar,Sunil Shetty,Shilpa Shetty,Drama Romance,2.740,2000,6.7,Akshay Kumar Sunil Shetty Shilpa Shetty Dharme...
...,...,...,...,...,...,...,...,...,...,...
1023,a daughter's tale pankh,Premraaj,Nishigandha Wad,Mehul Buch,Sudhir Pandey,Drama,0.600,2017,7.0,Nishigandha Wad Mehul Buch Sudhir Pandey Premr...
1024,kadvi hawa,Nila Madhab Panda,Sanjay Mishra,Ranvir Shorey,Tillotama Shome,Drama,1.201,2017,7.9,Sanjay Mishra Ranvir Shorey Tillotama Shome Ni...
1025,fukrey returns,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy Drama,1.616,2017,6.6,Pulkit Samrat Priya Anand Ali Fazal Mrighdeep ...
1026,game over,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Action Adventure Comedy Family Science Fiction,54.384,2017,5.1,Rajesh Sharma Yashpal Sharma Gurleen Chopra Pa...
1027,blackboard vs whiteboard,Tarun S. Bisht,Raghubir Yadav,Ashok Samarth,Akhilendra Mishra,Family,0.635,2019,7.0,Raghubir Yadav Ashok Samarth Akhilendra Mishra...

In [49]:
data.to_csv('bollywood_data1.csv',index=False)

In [50]:
data

,movie_title,director,actor_1,actor_2,actor_3,genres,popularity,year,ratings,combine
0,kuch kuch hota hai,Karan Johar,Shahrukh Khan,Kajol,Rani Mukerji,Romance Drama,11.704,2000,7.7,Shahrukh Khan Kajol Rani Mukerji Karan Johar R...
1,bichhoo,Guddu Dhanoa,Bobby Deol,Rani Mukerji,Malaika Arora,Action Crime Thriller,1.532,2000,4.8,Bobby Deol Rani Mukerji Malaika Arora Guddu Dh...
2,bulandi,Rama Rao Tatineni,Rajinikanth,Rekha,Anil Kapoor,Drama,1.454,2000,7.0,Rajinikanth Rekha Anil Kapoor Rama Rao Tatinen...
3,chal mere bhai,David Dhawan,Sanjay Dutt,Salman Khan,Karisma Kapoor,Romance Comedy,2.829,2000,4.8,Sanjay Dutt Salman Khan Karisma Kapoor David D...
4,dhadkan,Dharmesh Darshan,Akshay Kumar,Sunil Shetty,Shilpa Shetty,Drama Romance,2.740,2000,6.7,Akshay Kumar Sunil Shetty Shilpa Shetty Dharme...
...,...,...,...,...,...,...,...,...,...,...
1023,a daughter's tale pankh,Premraaj,Nishigandha Wad,Mehul Buch,Sudhir Pandey,Drama,0.600,2017,7.0,Nishigandha Wad Mehul Buch Sudhir Pandey Premr...
1024,kadvi hawa,Nila Madhab Panda,Sanjay Mishra,Ranvir Shorey,Tillotama Shome,Drama,1.201,2017,7.9,Sanjay Mishra Ranvir Shorey Tillotama Shome Ni...
1025,fukrey returns,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy Drama,1.616,2017,6.6,Pulkit Samrat Priya Anand Ali Fazal Mrighdeep ...
1026,game over,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Action Adventure Comedy Family Science Fiction,54.384,2017,5.1,Rajesh Sharma Yashpal Sharma Gurleen Chopra Pa...
1027,blackboard vs whiteboard,Tarun S. Bisht,Raghubir Yadav,Ashok Samarth,Akhilendra Mishra,Family,0.635,2019,7.0,Raghubir Yadav Ashok Samarth Akhilendra Mishra...

In [51]:
i = data.loc[data['movie_title']=='boss'].index[0]

In [52]:
i

719

In [45]:
link = "https://en.wikipedia.org/wiki/List_of_Hindi_films_of_2018"
df1 = pd.read_html(link, header=0)[4]

In [46]:
df1

,Opening,Opening.1,Title,Director,Cast,Production house,Ref.
0,JUL,6,Hanuman vs Mahiravana,Ezhil Vendan,NaN,Green Gold Animations,[74]
1,JUL,13,Soorma,Shaad Ali,"Diljit Dosanjh,Taapsee Pannu,Angad Bedi",Sony Pictures,[75]
2,JUL,20,When Obama Loved Osama,Sudhish Kumar Sharma,"Mousam Sharma,Swati Bakshi,Rahul Avana,Mohit B...",Shape Entertainment,[76]
3,JUL,20,Dhadak,Shashank Khaitan,"Ishaan Khatter,Jhanvi Kapoor",Dharma Productions,[77]
4,JUL,27,"Saheb, Biwi Aur Gangster 3",Tigmanshu Dhulia,"Sanjay Dutt,Jimmy Sheirgill,Mahi Gill,Chitrang...",Wave Cinemas,[78]
5,JUL,27,Nawabzaade,Jayesh Pradhan,"Raghav Juyal,Punit Pathak,Dharmesh Yelande,Ish...",Remo D'Souza Entertainment,[79]
6,AUG,3,Fanney Khan,Atul Manjrekar,"Anil Kapoor,Aishwarya Rai Bachchan,Rajkummar R...","T-Series, ROMP, AA Films",[80]
7,AUG,3,Mulk,Anubhav Sinha,"Rishi Kapoor,Prateik Babbar,Rajat Kapoor,Taaps...",Soham Rockstar Entertainment,[81]
8,AUG,3,Brij Mohan Amar Rahe!,Nikhil Bhatt,"Arjun Mathur,Nidhi Singh,Vijayant Kohli,Sunny ...",Yoodlee Films,[82]
9,AUG,3,Laxmi and Tikli Bomb,Aditya Kripalani,"Vibhawari Deshpande,Suchitra Pillai,Chitragand...",Mumba Devi Motion Pictures,[83]
10,AUG,3,Karwaan,Akarsh Khurana,"Irrfan Khan,Dulquer Salman,Mithila Palkar,Krit...",RSVP Movies,[84]
11,AUG,15,Gold,Reema Kagti,"Akshay Kumar,Kunal Kapoor,Mouni Roy,Amit Sadh",Excel Entertainment,[85][86]
12,AUG,15,Satyameva Jayate,Milap Zaveri,"John Abraham,Manoj Bajpayee,Aisha Sharma,Amrut...","T-Series, Emmay Entertainment",[87]
13,AUG,24,Genius,Anil Sharma,"Utkarsh Sharma,Ishita Chauhan,Nawazuddin Siddi...",Soham Rockstar Entertainment,[88]
14,AUG,24,Happy Phirr Bhag Jayegi,Mudassar Aziz,"Sonakshi Sinha,Diana Penty,Ali Fazal,Jimmy She...","Eros International, Colour Yellow Productions",[89]
15,AUG,24,Toba Tek Singh,Ketan Mehta,"Pankaj Kapur,Vinay Pathak",Maya Movies,[90]
16,AUG,31,Yamla Pagla Deewana: Phir Se,Navaniat Singh,"Dharmendra,Sunny Deol,Bobby Deol,Kriti Kharbanda",Pen India Limited,[91]
17,AUG,31,Stree,Amar Kaushik,"Rajkummar Rao,Shraddha Kapoor,Aparshakti Khura...","Maddock Films, D2R Films",[92]
18,SEP,1,Once Again,Kanwal Sethi,"Shefali Shah,Neeraj Kabi","Neufilm, JAR Pictures, Crawling Angel Films, A...",[93][94]
19,SEP,7,Paltan,J. P. Dutta,"Jackie Shroff,Sonu Sood,Arjun Rampal,Gurmeet C...","Zee Studios, J P Films",[95]
20,SEP,7,Laila Majnu,Sajid Ali,"Mir Sarwar,Avinash Tiwary,Tripti Dimri,Ruchika...","Pi Films, Balaji Motion Pictures",[96]
21,SEP,7,Gali Guleiyan,Dipesh Jain,"Manoj Bajpayee,Ranvir Shorey,Neeraj Kabi,Shaha...",PVR Pictures,[97]
22,SEP,7,Halkaa,Nila Madhab Panda,"Ranvir Shorey,Paoli Dam,Tathastu,Kumud Mishra","Shiv Nadar Foundation, Akshay Parija Productio...",[98]
23,SEP,14,Manmarziyaan,Anurag Kashyap,"Abhishek Bachchan,Vicky Kaushal,Taapsee Pannu","Eros International, Colour Yellow Productions,...",NaN
24,SEP,14,Love Sonia,Tabrez Noorani,"Mrunal Thakur,Freida Pinto,Manoj Bajpayee,Rajk...","Tamasha Talkies, Womark/Noorani Productions, L...",[99]
25,SEP,14,Mitron,Nitin Kakar,"Jackky Bhagnani,Kritika Kamra,Pratik Gandhi,Ne...",Abundantiya Entertainment,[100]
26,SEP,21,NaN,NaN,NaN,NaN,NaN
27,SEP,21,Batti Gul Meter Chalu,Shree Narayan Singh,"Shahid Kapoor,Shraddha Kapoor,Divyendu Sharma,...",T-Series,[101]
28,SEP,21,Manto,Nandita Das,"Nawazuddin Siddiqui,Tahir Raj Bhasin,Rasika Du...",Viacom 18 Motion Pictures,[102]
29,SEP,21,Ishqeria,Prerna Wadhawan,"Neil Nitin Mukesh,Richa Chaddha",Swarp Films & Yen Movies,[103]
30,SEP,28,Sui Dhaaga,Sharat Katariya,"Varun Dhawan,Anushka Sharma",Yash Raj Films,[104]
31,SEP,28,Pataakha,Vishal Bhardwaj,"Sanya Malhotra,Sunil Grover,Radhika Madan","Kayta Productions, Vishal Bhardwaj Films",[105]

In [ ]:
data.dropna

In [44]:
data

,movie_title,director,actor_1,actor_2,actor_3,genres,popularity,year,ratings,combine
0,kuch kuch hota hai,Karan Johar,Shahrukh Khan,Kajol,Rani Mukerji,Romance Drama,11.704,2000,7.7,Shahrukh Khan Kajol Rani Mukerji Karan Johar R...
1,bichhoo,Guddu Dhanoa,Bobby Deol,Rani Mukerji,Malaika Arora,Action Crime Thriller,1.532,2000,4.8,Bobby Deol Rani Mukerji Malaika Arora Guddu Dh...
2,bulandi,Rama Rao Tatineni,Rajinikanth,Rekha,Anil Kapoor,Drama,1.454,2000,7.0,Rajinikanth Rekha Anil Kapoor Rama Rao Tatinen...
3,chal mere bhai,David Dhawan,Sanjay Dutt,Salman Khan,Karisma Kapoor,Romance Comedy,2.829,2000,4.8,Sanjay Dutt Salman Khan Karisma Kapoor David D...
4,dhadkan,Dharmesh Darshan,Akshay Kumar,Sunil Shetty,Shilpa Shetty,Drama Romance,2.740,2000,6.7,Akshay Kumar Sunil Shetty Shilpa Shetty Dharme...
...,...,...,...,...,...,...,...,...,...,...
1023,a daughter's tale pankh,Premraaj,Nishigandha Wad,Mehul Buch,Sudhir Pandey,Drama,0.600,2017,7.0,Nishigandha Wad Mehul Buch Sudhir Pandey Premr...
1024,kadvi hawa,Nila Madhab Panda,Sanjay Mishra,Ranvir Shorey,Tillotama Shome,Drama,1.201,2017,7.9,Sanjay Mishra Ranvir Shorey Tillotama Shome Ni...
1025,fukrey returns,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy Drama,1.616,2017,6.6,Pulkit Samrat Priya Anand Ali Fazal Mrighdeep ...
1026,game over,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Action Adventure Comedy Family Science Fiction,54.384,2017,5.1,Rajesh Sharma Yashpal Sharma Gurleen Chopra Pa...
1027,blackboard vs whiteboard,Tarun S. Bisht,Raghubir Yadav,Ashok Samarth,Akhilendra Mishra,Family,0.635,2019,7.0,Raghubir Yadav Ashok Samarth Akhilendra Mishra...

In [13]:
data

,director,actor_1,actor_2,actor_3,genres,movie_title,popularity,year,combine
10,Milind Ukey,Siddharth Chandekar,Mrunmayi Deshpande,unknown,NaN,humne jeena seekh liya,0.600,2008,NaN
11,Rajkumar Santoshi,Ajay Devgn,Vidya Balan,Pankaj Kapur,Drama,halla bol,2.701,2008,Ajay Devgn Vidya Balan Pankaj Kapur Rajkumar S...
12,Eeshwar Nivas,Nikhil Dwivedi,Amrita Rao,Vishal O Sharma,Drama Comedy,my name is anthony gonsalves,1.398,2008,Nikhil Dwivedi Amrita Rao Vishal O Sharma Eesh...
13,Nagesh Kukunoor,Shreyas Talpade,Lena Christensen,Naseeruddin Shah,Comedy Romance Drama,bombay to bangkok,0.622,2008,Shreyas Talpade Lena Christensen Naseeruddin S...
14,K. Ajay Kumar,Irrfan Khan,Manisha Koirala,Arzoo Govitrikar,Drama,tulsi,1.208,2008,Irrfan Khan Manisha Koirala Arzoo Govitrikar K...
...,...,...,...,...,...,...,...,...,...
91,Saurabh Shrivastava,Vinay Pathak,Saurabh Shukla,Divya Dutta,Comedy,"oh, my god",7.638,2008,Vinay Pathak Saurabh Shukla Divya Dutta Saurab...
92,Aditya Chopra,Shah Rukh Khan,Anushka Sharma,Vinay Pathak,Comedy Drama Romance,rab ne bana di jodi,7.829,2008,Shah Rukh Khan Anushka Sharma Vinay Pathak Adi...
93,Rakesh Sawant,Rajesh Khanna,Laila Khan,Shahib Chopra,NaN,wafaa,0.600,2008,NaN
94,A. R. Murugadoss,Aamir Khan,Asin,Khalid Siddiqui,Action Romance Thriller,ghajini,6.163,2008,Aamir Khan Asin Khalid Siddiqui A. R. Murugado...
95,Kompin Kemgumnird,Akshay Kumar,Lara Dutta,Amar Babaria,Fantasy Romance,jumbo,4.520,2008,Akshay Kumar Lara Dutta Amar Babaria Kompin Ke...

## Extracting features of 2019 movies from Wikipedia

In [35]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [36]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [37]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,4,Escape Room,Columbia Pictures / Original Film,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,JANUARY,4,Rust Creek,IFC Films,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,JANUARY,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,JANUARY,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,JANUARY,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
237,DECEMBER,25,Spies in Disguise,20th Century Fox / Blue Sky Studios / Chernin ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[132]
238,DECEMBER,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[221]
239,DECEMBER,25,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[222]
240,DECEMBER,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[223]
241,DECEMBER,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[224]

In [38]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [39]:
df_2019 = df[['Title','Cast and crew','genres']]

In [40]:
df_2019

,Title,Cast and crew,genres
0,Escape Room,"Adam Robitel (director); Bragi F. Schut, Maria...",Horror Thriller Mystery
1,Rust Creek,Jen McGowan (director); Julie Lipson (screenpl...,Thriller Drama
2,American Hangman,Wilson Coneybeare (director/screenplay); Donal...,Thriller
3,A Dog's Way Home,Charles Martin Smith (director); W. Bruce Came...,Drama Adventure Family
4,The Upside,Neil Burger (director); Jon Hartmere (screenpl...,Comedy Drama
...,...,...,...
237,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Animation Action Adventure Comedy Family
238,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama Romance
239,1917,Sam Mendes (director/screenplay); Krysty Wilso...,War Drama Action Thriller
240,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama Crime History
241,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama

In [41]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [42]:
df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\Yash Sharma\Anaconda33\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [43]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [44]:
df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

C:\Users\Yash Sharma\Anaconda33\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [45]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [46]:
df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

C:\Users\Yash Sharma\Anaconda33\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [47]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [48]:
df_2019['actor_3_name'] = df_2019['Cast and crew'].map(lambda x: get_actor3(x))

In [49]:
df_2019 = df_2019.rename(columns={'Title':'movie_title'})

In [50]:
new_df19 = df_2019.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [51]:
new_df19['actor_2_name'] = new_df19['actor_2_name'].replace(np.nan, 'unknown')
new_df19['actor_3_name'] = new_df19['actor_3_name'].replace(np.nan, 'unknown')

In [52]:
new_df19['movie_title'] = new_df19['movie_title'].str.lower()

In [53]:
new_df19['comb'] = new_df19['actor_1_name'] + ' ' + new_df19['actor_2_name'] + ' '+ new_df19['actor_3_name'] + ' '+ new_df19['director_name'] +' ' + new_df19['genres']

In [54]:
new_df19

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll,Horror Thriller Mystery,escape room,Taylor Russell Logan Miller Deborah Ann Woll A...
1,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,Thriller Drama,rust creek,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Thriller,american hangman,Donald Sutherland Vincent Kartheiser Oliver De...
3,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,Drama Adventure Family,a dog's way home,Bryce Dallas Howard Edward James Olmos Alexand...
4,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman,Comedy Drama,the upside,Bryan Cranston Kevin Hart Nicole Kidman Neil B...
...,...,...,...,...,...,...,...
237,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
238,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
239,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917,George MacKay Dean-Charles Chapman Mark Strong...
240,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
241,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [55]:
my_df = new_df18.append(new_df19,ignore_index=True)

In [56]:
my_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama History Western,sweet country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
509,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
510,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
511,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917,George MacKay Dean-Charles Chapman Mark Strong...
512,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
513,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [58]:
old_df = pd.read_csv('datasets/data_2017.csv')

In [59]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5359,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5360,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5361,Hannaleena Hauru,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mäntyvaara,Inka Haapamäki Rosa Honkonen Tiitus Rantala Ha...
5362,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5363,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [60]:
final_df = old_df.append(my_df,ignore_index=True)

In [61]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5873,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
5874,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
5875,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917,George MacKay Dean-Charles Chapman Mark Strong...
5876,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
5877,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [62]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           1
movie_title      0
comb             1
dtype: int64

In [63]:
final_df = final_df.dropna(how='any')

In [64]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [65]:
final_df.to_csv('datasets/data_2019.csv',index=False)

In [3]:
link = "https://en.wikipedia.org/wiki/List_of_Hindi_films_of_"+'2000'
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

C:\Users\Yash Sharma\Anaconda33\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

In [4]:
df

,Cast,Director,Genre,Hindi cinema,Music director,Rank,Title,vteIndian films by year and decade,vteIndian films by year and decade.1
0,NaN,NaN,NaN,1920s,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,1920 1921 1922 1923 19241925 1926 1927 1928 1929,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,1930s,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,1930 1931 1932 1933 19341935 1936 1937 1938 1939,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,1940s,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Odia,1936 1949 1950 1951 1953 1954 1956 1959 1960 1...
126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tamil,1930s 1940 1941 1942 1943 1944 1945 1946 1947 ...
127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Telugu,1930s 1940 1941 1942 1943 1944 1945 1946 1947 ...
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other,Assamese Punjabi
129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Related,Silent films of South India